__app_name__ = "USync-GPhotos"
__version__ = "0.1.0"
__description__ = "USync-GPhotos is a tool to synchronize Google Photos to a local folder"
__author__ = "Septimiu Ujica"
__author_email__ = "me@septi.ro"
__author_url__ = "https://www.septi.ro"
__license__ = "GPLv3"
